dropout: 0.07800932022121826
group_identifier: gauge_id
hidden_size: 124
input_len: 64
input_size: 10
learning_rate: 0.00015751320499779721
lr_scheduler_factor: 0.5
lr_scheduler_patience: 5
num_layers: 8
output_len: 10
static_embedding_size: 10
static_size: 10
