dropout: 0.3259332753890891
group_identifier: gauge_id
hidden_size: 99
input_len: 63
input_size: 10
learning_rate: 0.0008127134882347091
lr_scheduler_factor: 0.5
lr_scheduler_patience: 5
num_layers: 4
output_len: 10
static_embedding_size: 10
static_size: 10
