dropout: 0.09091248360355031
group_identifier: gauge_id
hidden_size: 126
input_len: 31
input_size: 10
learning_rate: 2.6587543983272695e-05
lr_scheduler_factor: 0.5
lr_scheduler_patience: 5
num_layers: 9
output_len: 10
static_embedding_size: 10
static_size: 10
