dropout: 0.14561457009902096
group_identifier: gauge_id
hidden_size: 61
input_len: 46
input_size: 10
learning_rate: 7.309539835912905e-05
lr_scheduler_factor: 0.5
lr_scheduler_patience: 5
num_layers: 6
output_len: 10
static_embedding_size: 10
static_size: 10
