discriminator_hidden_dim: 32
domain_loss_weight: 0.5
dropout: 0.4
group_identifier: gauge_id
hidden_size: 64
initial_lambda: 0.0
input_len: 80
input_size: 10
lambda_adv: 1.0
learning_rate: 2.0e-05
lr_scheduler_factor: 0.5
lr_scheduler_patience: 5
num_layers: 6
output_len: 10
static_embedding_size: 5
static_size: 10
target_loss_weight: 1.0
use_target_labels: true
use_zero_static: false
