dropout: 0.22803499210851796
group_identifier: gauge_id
hidden_size: 45
input_len: 85
input_size: 10
learning_rate: 5.4041038546473305e-05
lr_scheduler_factor: 0.5
lr_scheduler_patience: 5
num_layers: 4
output_len: 10
static_embedding_size: 10
static_size: 10
