dropout: 0.35403628889802274
group_identifier: gauge_id
hidden_size: 37
input_len: 44
input_size: 10
learning_rate: 0.00015930522616241006
lr_scheduler_factor: 0.5
lr_scheduler_patience: 5
num_layers: 9
output_len: 10
static_embedding_size: 10
static_size: 10
