dropout: 0.4828160165372797
group_identifier: gauge_id
hidden_size: 48
input_len: 85
input_size: 10
learning_rate: 0.000790261954970823
lr_scheduler_factor: 0.5
lr_scheduler_patience: 5
num_layers: 2
output_len: 10
static_embedding_size: 10
static_size: 10
