dropout: 0.3
group_identifier: gauge_id
hidden_size: 32
input_len: 128
input_size: 10
learning_rate: 0.0003
lr_scheduler_factor: 0.5
lr_scheduler_patience: 3
num_layers: 10
output_len: 10
static_embedding_size: 10
static_size: 10
