dropout: 0.09242722776276352
group_identifier: gauge_id
hidden_size: 62
input_len: 90
input_size: 10
learning_rate: 0.00012399967836846095
lr_scheduler_factor: 0.5
lr_scheduler_patience: 5
num_layers: 6
output_len: 10
static_embedding_size: 10
static_size: 10
